// AUTH

# @name login
@authToken = {{ login.response.body.authenticated.jwtToken }}
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

###

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "username": "admin"
}

###

// EMPLOYEES

GET http://localhost:3000/employees
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

GET http://localhost:3000/employees/64c7d7173df26d7f9fd2c15
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

POST http://localhost:3000/employees/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "firstName": "loll",
    "lastName": "loll",
    "dob": "1991-12-05",
    "email": "1833@hotmail.com",
    "isActive": true,
    "skillLevels": []
}

###

PUT  http://localhost:3000/employees/64c8ed3753fe76841d2b2998
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "firstName": "qwqwqwqwqw",
    "lastName": "Updated",
    "dob": "1992-12-05",
    "email": "1833@hotmail.com",
    "isActive": true,
    "skillLevels": []
}

###
DELETE  http://localhost:3000/employees/64bfb54cb50d94e9c7f37e8f
Authorization: Bearer {{authToken}}
Content-Type: application/json

####################################################################

// SKILL LEVEL

GET http://localhost:3000/skillLevels
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

GET http://localhost:3000/skillLevels/64c8e3fc78e47fb0c24d3430
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

POST http://localhost:3000/skillLevels
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "TEST",
    "description": "TEST"
}

###

PUT  http://localhost:3000/skillLevels/64c8e7b7d4f0fda9090da467
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Communication",
    "description": "taa"
}

###
DELETE  http://localhost:3000/skillLevels/64bfcdc5f8ca9e848af2a03d
Authorization: Bearer {{authToken}}
Content-Type: application/json

####################################################################

// USER

GET http://localhost:3000/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

GET http://localhost:3000/users/64bfd1d6b256346461dec8f5
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123"
}

###

PUT  http://localhost:3000/users/64bfd1d6b256346461dec8f5
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "username": "a",
    "password": "updated user"
}

###
DELETE  http://localhost:3000/users/64bfdbd5e33c20f2febfbdec
Authorization: Bearer {{authToken}}
Content-Type: application/json