// AUTH

# @name login
@authToken = {{ login.response.body.authenticated.jwtToken }}
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin123",
    "password": "Admin123!"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

###

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "username": "admin"
}

###

// EMPLOYEES

GET http://localhost:3000/employees
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

GET http://localhost:3000/employees/64c7d7173df26d7f9fd2c15
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

POST http://localhost:3000/employees/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "firstName": "Gerry 2",
    "lastName": "Roger 2",
    "dob": "1991-12-05",
    "email": "123@hotmail.com",
    "isActive": true,
    "skillLevels": ["64ca17aa7c562a5d2f470431"]
}

###

PUT  http://localhost:3000/employees/64ca10d4cb304ef19ac9fb82
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "firstName": "Brian",
    "lastName": "McKenna",
    "dob": "1992-12-05",
    "email": "18334@hotmail.com",
    "isActive": true,
    "skillLevels": ["64c92d9c78e47fb0c24d3488", "64c92d9c78e47fb0c24d3489"]
}

###
DELETE  http://localhost:3000/employees/64bfb54cb50d94e9c7f37e8f
Authorization: Bearer {{authToken}}
Content-Type: application/json

####################################################################

// SKILL LEVEL

GET http://localhost:3000/skillLevels
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

GET http://localhost:3000/skillLevels/64c8e3fc78e47fb0c24d3430
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

POST http://localhost:3000/skillLevels
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "TEST",
    "description": "TEST"
}

###

PUT  http://localhost:3000/skillLevels/64c8e3fc78e47fb0c24d3434
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Communication",
    "description": "taa"
}

###
DELETE  http://localhost:3000/skillLevels/64c92d9c78e47fb0c24d3488
Authorization: Bearer {{authToken}}
Content-Type: application/json

####################################################################

// USER

GET http://localhost:3000/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

GET http://localhost:3000/users/64bfd1d6b256346461dec8f5
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "admin123",
    "password": "Admin123!"
}

###

PUT  http://localhost:3000/users/64c8f606952ac274448f6e8e
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "username": "admin1",
    "password": "updated"
}

###
DELETE  http://localhost:3000/users/64c8e3fc78e47fb0c24d3432
Authorization: Bearer {{authToken}}
Content-Type: application/json